Demo of using twitter-hashtag-analytics package to analyze tweets
========================================================

1. Data preparation
-----------------------

First thing first:

```{r preparation}
# set working directory
setwd("~/src/r/twitter-analytics/twitter-hashtag-analytics")

# load source files
source("get_tweets.R")
source("munge_tweets.R")
source("utilities.R")
```

Retrieve a Twitter hashtag dataset by search:

```{r getbysearch}
# get tweets by search
df <- GetTweetsBySearch('#LAK13')

# check names of columns
names(df)

# how many unique Twitter accounts in the dataset
length(unique(df$screenName))
```

Some pre-processing tasks:

```{r preprocess}
# removing odd characters
df <- RemoveOddChars(df)
# extract user info and add to df
df <- ExtractUserInfo(df)
```

2. Count stuff
----------------------

```{r counttables}
library(ggplot2)
library(reshape2)

# Count tables
countsSortSubset <- GetTweetCountTable(df, "screenName")
countRTSortSubset <- GetTweetCountTable(df, "rt")
countToSortSubset <- GetTweetCountTable(df, "to")

# combine counts into one data frame
counts1 <- merge(countsSortSubset, countRTSortSubset, by = "user", all.x=TRUE)
counts <- merge(counts1, countToSortSubset, by = "user", all.x = TRUE)
colnames(counts) <- c("user", "tweets", "to", "rt")
counts[is.na(counts)] <- 0
counts$tweets <- as.numeric(counts$tweets)
counts$to <- as.numeric(counts$to)
counts$rt <- as.numeric(counts$rt)

# melt data
counts.melt <- melt(counts, id.vars = c("user"))

# plot (Cleveland dot plot)
ggplot(counts.melt, aes(x = user, y = value, color = variable)) + 
  geom_point() + geom_line() + coord_flip() + ggtitle("Graph")
```
